name: DartTest
description: A simple StageXL web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Bee <pizzaman8099@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  stagexl: ^1.4.0
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  sass_builder: ^2.1.2
